#!/bin/bash
# Git pre-commit hook will check whether the branch name is correct using a regular expression.

LC_ALL=C

LOCAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
VALID_BRANCH_REGEX="^(feature|release|hotfix)\/[a-zA-Z0-9._-]+$"
PROTECTED_BRANCHES="^(master|dev|develop|staging)"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $VALID_BRANCH_REGEX. Your commit will be rejected by pre-commit hook. You should rename your branch to a valid name and try again."

if [[ $LOCAL_BRANCH =~ $PROTECTED_BRANCHES ]]; then
	echo "$Committing changes"
  exit 0
fi

if [[ ! $LOCAL_BRANCH =~ $VALID_BRANCH_REGEX ]]
then
    echo "$message"
    echo "Please rename your current branch by doing :"
    echo "git branch -m <old-name> <new-name>"
    exit 1
fi

exit 0